import { notifications as mockNotifications } from '../../services/mock-data.js';
import { listMyNotifications, markNotificationRead } from '../../services/notifications-repository.js';
import { appMode } from '../../services/supabase.js';
import { escapeHtml } from '../../utils/html.js';

let items=[];
export async function renderNotifications() {
  if(appMode==='supabase'){
    const rows=await listMyNotifications();
    items=rows.map(r=>({id:r.notifications.id,kind:r.notifications.type,priority:r.notifications.priority||0,read:Boolean(r.read_at),title:r.notifications.title,text:r.notifications.body,dateLabel:new Date(r.notifications.created_at).toLocaleString('es-UY'),href:r.notifications.target_path||'/notificaciones'}));
  } else items=mockNotifications;
  return `<section class="module-head"><div><span class="eyebrow">Centro de avisos</span><h1>Notificaciones</h1><p>Todo lo que requiere tu atención, con acceso directo al contenido relacionado.</p></div><button class="button ghost" id="mark-all-read">Marcar todo como leído</button></section><div class="tabs"><button class="tab active" data-notification-filter="todas">Todas</button><button class="tab" data-notification-filter="importantes">Importantes</button><button class="tab" data-notification-filter="tramites">Trámites</button></div><section class="notification-layout section"><div class="notification-list" id="notification-list">${cards(items)}</div><aside class="card notification-settings"><span class="eyebrow">Preferencias</span><h2>Qué querés recibir</h2><p class="settings-note">Las preferencias se almacenarán en tu perfil; los avisos institucionales críticos pueden mantenerse activos.</p></aside></section>`;
}
function cards(arr){if(!arr.length)return `<div class="card empty-state"><h3>No hay notificaciones</h3><p>Todo está al día.</p></div>`;return arr.map(n=>`<a href="#${escapeHtml(n.href)}" class="card notification-card ${n.read?'':'unread'}" data-notification-id="${n.id}" data-kind="${n.kind}" data-priority="${n.priority}"><div class="notification-symbol">${symbol(n.kind)}</div><div><div class="notification-line"><strong>${escapeHtml(n.title)}</strong>${!n.read?'<span class="unread-dot"></span>':''}</div><p>${escapeHtml(n.text)}</p><small>${escapeHtml(n.dateLabel)}</small></div><span class="notification-arrow">›</span></a>`).join('')}
function symbol(kind){return ({tramite:'▤',institucional:'!',convenio:'%',evento:'◷',documento:'▧'})[kind]||'•'}
export function bindNotifications(){const tabs=[...document.querySelectorAll('[data-notification-filter]')];tabs.forEach(tab=>tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.toggle('active',t===tab));const f=tab.dataset.notificationFilter;document.querySelectorAll('[data-notification-id]').forEach(c=>c.hidden=!(f==='todas'||(f==='importantes'&&Number(c.dataset.priority)>=8)||(f==='tramites'&&c.dataset.kind==='tramite')))}));document.querySelector('#notification-list')?.addEventListener('click',async e=>{const c=e.target.closest('[data-notification-id]');if(c&&!c.classList.contains('read')){try{await markNotificationRead(c.dataset.notificationId)}catch(err){console.error(err)}}});document.querySelector('#mark-all-read')?.addEventListener('click',async()=>{for(const n of items.filter(x=>!x.read)){try{await markNotificationRead(n.id);n.read=true}catch(e){console.error(e)}}document.querySelector('#notification-list').innerHTML=cards(items)})}
