import { demoRequests } from '../../services/mock-data.js';
import { listRequestDefinitions, getRequestDefinition } from '../../services/request-definitions-repository.js';
import { listMyRequests, getMyRequest, saveDraft, submitRequest } from '../../services/requests-repository.js';
import { uploadRequestFile, getRequestFileUrl } from '../../services/storage-service.js';
import { appMode, requireSupabase } from '../../services/supabase.js';
import { escapeHtml } from '../../utils/html.js';
import { navigate } from '../../router/router.js';
import { getSession } from '../../store/session.js';

let currentDefinition=null;
let draftTimer=null;

export async function renderTramites() {
  const definitions=await listRequestDefinitions();
  const requests=appMode==='supabase'?await listMyRequests():demoRequests;
  return `<div class="page-title split"><div><span class="eyebrow">Gestiones</span><h1>Trámites</h1><p>Iniciá una solicitud, guardala como borrador y seguí cada movimiento desde un único lugar.</p></div>${definitions[0]?`<a class="button secondary" href="#/tramites/nuevo/${encodeURIComponent(definitions[0].id)}">+ Nueva solicitud</a>`:''}</div><section class="request-layout"><div><div class="section-head"><h2>¿Qué necesitás hacer?</h2><span class="muted">${definitions.length} trámites disponibles</span></div><div class="request-grid">${definitions.map(requestType).join('')}</div></div><aside><div class="section-head"><h2>Mis solicitudes</h2><span class="muted">${requests.length}</span></div>${requests.length?requests.map(requestSummary).join(''):'<article class="card empty-state"><h3>No tenés solicitudes</h3><p>Cuando inicies una gestión aparecerá acá.</p></article>'}<article class="card draft-card"><span class="eyebrow">Borradores</span><h3>Guardado automático</h3><p>En Supabase, los formularios en curso se sincronizan con tu cuenta.</p></article></aside></section>`;
}

export async function renderNewRequest(id) {
  currentDefinition=await getRequestDefinition(id);
  if(!currentDefinition)return notFound('Trámite no encontrado');
  const d=currentDefinition;
  return `<a class="back-link" href="#/tramites">← Volver a Trámites</a><div class="page-title"><div><span class="eyebrow">Nuevo trámite</span><h1>${escapeHtml(d.name)}</h1><p>${escapeHtml(d.description)}</p></div></div><section class="form-flow" data-request-form="${escapeHtml(d.id)}"><div class="form-main card"><div class="stepper">${d.steps.map((s,i)=>`<div class="step ${i===0?'active':''}" data-step-indicator="${i}"><span>${i+1}</span><small>${escapeHtml(s.title)}</small></div>`).join('')}</div><form id="request-form">${d.steps.map((s,i)=>renderStep(s,i,d.steps.length)).join('')}</form></div><aside class="card form-summary"><span class="eyebrow">Resumen</span><h2>${escapeHtml(d.name)}</h2><dl class="detail-list"><div><dt>Tiempo estimado</dt><dd>${escapeHtml(d.estimated)}</dd></div><div><dt>Tipo</dt><dd>${d.automatic?'Automática con validación':'Revisión administrativa'}</dd></div><div><dt>Guardado</dt><dd>${appMode==='supabase'?'Borrador sincronizado con tu cuenta':'Borrador de demostración'}</dd></div></dl><div class="privacy-note">No envíes información que el trámite no solicite expresamente.</div></aside></section>`;
}

export function bindNewRequest(){const root=document.querySelector('[data-request-form]');if(!root||!currentDefinition)return;const form=root.querySelector('#request-form');const steps=[...root.querySelectorAll('[data-step-panel]')];let current=0;const show=i=>{current=Math.max(0,Math.min(i,steps.length-1));steps.forEach((s,j)=>s.hidden=j!==current);root.querySelectorAll('[data-step-indicator]').forEach((x,j)=>{x.classList.toggle('active',j===current);x.classList.toggle('done',j<current)});root.querySelectorAll('[data-step-counter]').forEach(x=>x.textContent=`${current+1} de ${steps.length}`)};root.addEventListener('click',e=>{const next=e.target.closest('[data-next]'),prev=e.target.closest('[data-prev]');if(next){e.preventDefault();const required=[...steps[current].querySelectorAll('[required]')];if(required.some(x=>x.type!=='file'&&!x.value)){required.forEach(x=>x.classList.toggle('field-error',x.type!=='file'&&!x.value));return}show(current+1)}if(prev){e.preventDefault();show(current-1)}});form?.addEventListener('input',()=>{clearTimeout(draftTimer);draftTimer=setTimeout(()=>persistDraft(form,current),700)});form?.addEventListener('submit',async e=>{e.preventDefault();const state=root.querySelector('[data-submit-state]');try{state.innerHTML='<button class="button primary" disabled>Enviando…</button>';const payload=payloadFrom(form);const result=await submitRequest(currentDefinition.databaseId||currentDefinition.id,payload);if(appMode==='supabase'){const files=[...form.querySelectorAll('input[type=file]')].flatMap(input=>[...(input.files||[])]);for(const file of files)await uploadRequestFile(result.id,file)}state.innerHTML=`<div class="success-panel"><span>✓</span><div><strong>Solicitud enviada</strong><p>${result.request_number==='DEMO'?'Modo demostración':`Expediente ${escapeHtml(result.request_number)}`}</p></div></div>`;if(appMode==='supabase')setTimeout(()=>navigate(`/solicitudes/${result.id}`),900)}catch(err){console.error(err);state.innerHTML='<div class="error-panel"><strong>No se pudo enviar.</strong><p>Revisá la conexión e intentá nuevamente.</p><button class="button primary" type="submit">Reintentar</button></div>'}});show(0)}

async function persistDraft(form,currentStep){if(!currentDefinition)return;try{await saveDraft(currentDefinition.databaseId||currentDefinition.id,payloadFrom(form),currentStep)}catch(e){console.warn('No se pudo guardar borrador',e)}}
function payloadFrom(form){const out={};for(const [k,v] of new FormData(form).entries()){if(v instanceof File)continue;out[k]=v}return out}

export async function renderRequestDetail(id){let r;if(appMode==='supabase')r=await getMyRequest(id);else r=demoRequests.find(x=>x.id===id);if(!r)return notFound('Solicitud no encontrada');if(appMode!=='supabase')return demoDetail(r);const events=(r.request_events||[]).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const messages=(r.request_messages||[]).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const files=r.request_files||[];const myProfileId=getSession()?.profile?.id;return `<a class="back-link" href="#/tramites">← Volver a Trámites</a><div class="page-title split"><div><span class="eyebrow">Seguimiento</span><h1>${escapeHtml(r.request_definitions?.name||'Solicitud')}</h1><p>${escapeHtml(r.request_number)} · ${formatDate(r.submitted_at||r.created_at)}</p></div><span class="pill info">${escapeHtml(statusLabel(r.status))}</span></div><section class="tracking-layout"><article class="card tracking-card"><div class="section-head"><div><span class="eyebrow">Estado del trámite</span><h2>Seguimiento</h2></div></div><div class="tracking-timeline">${events.length?events.map((e,i)=>`<div class="tracking-event ${i===events.length-1?'current':'done'}"><span></span><div><strong>${escapeHtml(eventLabel(e.event_type))}</strong><small>${formatDate(e.created_at)}</small><p>${escapeHtml(e.message||'')}</p></div></div>`).join(''):'<p class="muted">Todavía no hay movimientos visibles.</p>'}</div></article><aside><article class="card"><span class="eyebrow">Mensajes</span><div class="message-list">${messages.length?messages.map(m=>`<div class="message"><strong>${m.author_profile_id===myProfileId?'Vos':m.author_profile_id?'AFUCOA':'Sistema'}</strong><small>${formatDate(m.created_at)}</small><p>${escapeHtml(m.body||m.message||m.text||'')}</p></div>`).join(''):'<p class="muted">Sin mensajes.</p>'}</div><label class="message-compose">Agregar mensaje<textarea id="request-message" placeholder="Aportá información relevante."></textarea><button class="button secondary" type="button" data-send-request-message="${escapeHtml(r.id)}">Enviar mensaje</button></label></article><article class="card"><span class="eyebrow">Documentos</span><div id="request-file-list">${files.length?files.map(f=>`<button class="file-link" data-file-path="${escapeHtml(f.storage_path)}">▧ ${escapeHtml(f.file_name)}</button>`).join(''):'<p class="muted">Sin archivos adjuntos.</p>'}</div></article></aside></section>`}

export function bindRequestDetail(){document.querySelector('[data-send-request-message]')?.addEventListener('click',async e=>{const button=e.currentTarget;const textarea=document.querySelector('#request-message');const text=textarea?.value.trim();if(!text)return;button.disabled=true;button.textContent='Enviando…';try{const db=requireSupabase();const profileId=getSession()?.profile?.id;if(!profileId)throw new Error('Perfil no disponible');const {error}=await db.from('request_messages').insert({request_id:button.dataset.sendRequestMessage,author_profile_id:profileId,body:text,visible_to_member:true});if(error)throw error;button.textContent='Enviado';textarea.value='';const list=document.querySelector('.message-list');list?.querySelector('.muted')?.remove();list?.insertAdjacentHTML('beforeend',`<div class="message"><strong>Vos</strong><small>${formatDate(new Date())}</small><p>${escapeHtml(text)}</p></div>`)}catch(err){console.error(err);button.textContent='Error'}finally{button.disabled=false}});document.querySelector('#request-file-list')?.addEventListener('click',async e=>{const btn=e.target.closest('[data-file-path]');if(!btn)return;try{const url=await getRequestFileUrl(btn.dataset.filePath);if(url)window.location.assign(url);else throw new Error('No se generó el enlace temporal.')}catch(err){console.error(err)}})}

function renderStep(step,index,total){const review=!step.fields?.length;return `<section class="step-panel" data-step-panel="${index}" ${index===0?'':'hidden'}><div class="step-panel-head"><div><span class="eyebrow">Paso <span data-step-counter>${index+1} de ${total}</span></span><h2>${escapeHtml(step.title)}</h2></div></div>${review?reviewPanel():`<div class="form-fields">${step.fields.map(field).join('')}</div>`}<div class="flow-actions"><button class="button tertiary" data-prev ${index===0?'disabled':''}>Atrás</button>${index===total-1?'<div data-submit-state><button class="button primary" type="submit">Enviar solicitud</button></div>':'<button class="button primary" data-next>Continuar</button>'}</div></section>`}
function field(x){const req=x.required?'required':'';const label=`${escapeHtml(x.label||x.name)}${x.required?'<em>*</em>':''}`;if(x.type==='textarea')return `<label class="field">${label}<textarea name="${escapeHtml(x.name)}" placeholder="${escapeHtml(x.placeholder||'')}" ${req}></textarea></label>`;if(x.type==='select')return `<label class="field">${label}<select name="${escapeHtml(x.name)}" ${req}><option value="">Seleccioná una opción</option>${(x.options||[]).map(o=>`<option value="${escapeHtml(o)}">${escapeHtml(o)}</option>`).join('')}</select></label>`;if(x.type==='file')return `<label class="field file-field">${label}<input type="file" name="${escapeHtml(x.name)}" accept=".pdf,.jpg,.jpeg,.png" ${req}><span>Seleccionar archivo</span><small>PDF, JPG o PNG · máximo 10 MB.</small></label>`;return `<label class="field">${label}<input type="${escapeHtml(x.type||'text')}" name="${escapeHtml(x.name)}" placeholder="${escapeHtml(x.placeholder||'')}" ${req}></label>`}
function reviewPanel(){return `<div class="review-panel"><div class="review-icon">✓</div><div><h3>Revisá la información antes de enviar</h3><p>Al confirmar se crea el expediente y luego se suben los adjuntos de forma privada.</p></div></div>`}
function requestType(x,i){return `<article class="card request-type"><div class="quick-icon">${i+1}</div><div><span class="category-tag">${escapeHtml(x.category)}</span><h3>${escapeHtml(x.name)}</h3><p>${escapeHtml(x.description)}</p><small class="request-estimate">${escapeHtml(x.estimated)}</small></div><a class="button secondary" href="#/tramites/nuevo/${encodeURIComponent(x.id)}">Iniciar</a></article>`}
function requestSummary(x){const id=x.id;const number=x.request_number||x.id;const title=x.request_definitions?.name||x.title||'Solicitud';const status=x.statusLabel||statusLabel(x.status);return `<article class="card request-summary"><span class="pill info">${escapeHtml(status)}</span><h3>${escapeHtml(title)}</h3><p>${escapeHtml(number)}</p><a class="button primary wide" href="#/solicitudes/${encodeURIComponent(id)}">Ver seguimiento</a></article>`}
function demoDetail(r){return `<a class="back-link" href="#/tramites">← Volver a Trámites</a><div class="page-title split"><div><span class="eyebrow">Seguimiento</span><h1>${escapeHtml(r.title)}</h1><p>${escapeHtml(r.id)} · ${escapeHtml(r.createdAt)}</p></div><span class="pill info">${escapeHtml(r.statusLabel)}</span></div><section class="tracking-layout"><article class="card tracking-card"><div class="tracking-timeline">${r.events.map(e=>`<div class="tracking-event ${e.state}"><span></span><div><strong>${escapeHtml(e.label)}</strong><small>${escapeHtml(e.date)}</small><p>${escapeHtml(e.detail)}</p></div></div>`).join('')}</div></article><aside><article class="card"><span class="eyebrow">Mensajes</span>${r.messages.map(m=>`<div class="message"><strong>${escapeHtml(m.author)}</strong><small>${escapeHtml(m.date)}</small><p>${escapeHtml(m.text)}</p></div>`).join('')}</article></aside></section>`}
function statusLabel(s){return ({borrador:'Borrador',recibida:'Recibida',en_revision:'En revisión',requiere_informacion:'Requiere información',en_gestion:'En gestión',resuelta:'Resuelta',cancelada:'Cancelada'})[s]||s||'Pendiente'}
function eventLabel(s){return ({submitted:'Solicitud recibida',status_changed:'Estado actualizado',message:'Mensaje',file_added:'Documento agregado'})[s]||'Actualización'}
function formatDate(v){return v?new Date(v).toLocaleString('es-UY'):'—'}
function notFound(t){return `<div class="empty-state card"><h1>${escapeHtml(t)}</h1><p>No encontramos el registro solicitado.</p><a class="button primary" href="#/tramites">Volver a Trámites</a></div>`}
