import { listDocuments } from '../../services/documents-repository.js';
import { getPrivateDocumentUrl } from '../../services/storage-service.js';
import { escapeHtml } from '../../utils/html.js';

let documents=[];
export async function renderDocuments() {
  documents=await listDocuments();
  const categories=['Todos', ...new Set(documents.map(d=>d.category))];
  return `<section class="module-head"><div><span class="eyebrow">Biblioteca documental</span><h1>Documentos</h1><p>Reglamentos, actas, comunicados y formularios en un único lugar.</p></div><span class="pill">${documents.length} documentos</span></section><section class="library-toolbar card"><label class="search-wrap big"><span>⌕</span><input id="document-search" class="search" placeholder="Buscar por título, categoría o versión" aria-label="Buscar documentos"></label><div class="chips compact" id="document-categories">${categories.map((c,i)=>`<button class="chip ${i===0?'active':''}" data-document-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('')}</div></section><section class="section"><div class="section-head"><h2>Biblioteca</h2><small class="muted">Los PDFs se entregan mediante enlaces temporales cuando son privados.</small></div><div class="document-grid" id="document-grid">${documentCards(documents)}</div></section>`;
}
function documentCards(items){if(!items.length)return `<div class="card empty-state"><h3>No encontramos documentos</h3><p>Probá con otra búsqueda o categoría.</p></div>`;return items.map(doc=>`<article class="card document-card" data-document-card data-search="${escapeHtml(`${doc.title} ${doc.category} ${doc.version}`.toLowerCase())}" data-category="${escapeHtml(doc.category)}"><div class="document-icon">PDF</div><div class="document-body"><div class="document-meta"><span class="category-tag">${escapeHtml(doc.category)}</span>${doc.current?'<span class="pill success-soft">Vigente</span>':'<span class="pill">Archivado</span>'}</div><h3>${escapeHtml(doc.title)}</h3><p>${escapeHtml(doc.description)}</p><small>${escapeHtml(doc.version)} · ${escapeHtml(doc.dateLabel)}</small></div><div class="document-actions"><button class="button ghost" type="button" data-open-document="${escapeHtml(doc.storage_path||'')}">Ver</button><button class="icon-button" type="button" aria-label="Guardar favorito">☆</button></div></article>`).join('')}
export function bindDocuments(){const search=document.querySelector('#document-search');const chips=[...document.querySelectorAll('[data-document-category]')];let category='Todos';const apply=()=>{const q=(search?.value||'').trim().toLowerCase();document.querySelectorAll('[data-document-card]').forEach(card=>{const matchesText=!q||card.dataset.search.includes(q);const matchesCategory=category==='Todos'||card.dataset.category===category;card.hidden=!(matchesText&&matchesCategory)})};search?.addEventListener('input',apply);chips.forEach(chip=>chip.addEventListener('click',()=>{category=chip.dataset.documentCategory;chips.forEach(c=>c.classList.toggle('active',c===chip));apply()}));document.querySelector('#document-grid')?.addEventListener('click',async e=>{const button=e.target.closest('[data-open-document]');if(!button)return;const path=button.dataset.openDocument;if(!path){button.textContent='Demo';return}try{button.disabled=true;button.textContent='Abriendo…';const url=await getPrivateDocumentUrl(path);if(url)window.open(url,'_blank','noopener');button.textContent='Ver'}catch(err){console.error(err);button.textContent='Error'}finally{button.disabled=false}})}
